#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
. "$(dirname -- "$0")/common.sh"
. "$(dirname "$0")/../git-hooks/pre-console.sh"
. "$(dirname "$0")/../git-hooks/pre-image-optimize.sh"

images=$(git diff --exit-code --cached --name-only --diff-filter=ACM -- '*.png' '*.jpg' '*.jpeg')

$(exit $?) || (echo "$images" | ~/.image-opt/imageoptim-cli/bin/imageOptim && git add $images)

yarn format && yarn lint:fix
